# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("calculator.proto", :syntax => :proto3) do
    add_message "grpc.demo.FibonacciParams" do
      optional :n, :int32, 1
    end
    add_message "grpc.demo.NthFibonacciResponse" do
      optional :result, :int32, 1
    end
    add_message "grpc.demo.SubstringsParams" do
      optional :str, :string, 1
    end
    add_message "grpc.demo.SubstringsResponse" do
      repeated :substrings, :string, 1
    end
  end
end

module Grpc
  module Demo
    FibonacciParams = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc.demo.FibonacciParams").msgclass
    NthFibonacciResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc.demo.NthFibonacciResponse").msgclass
    SubstringsParams = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc.demo.SubstringsParams").msgclass
    SubstringsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc.demo.SubstringsResponse").msgclass
  end
end
