// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CalculatorClient is the client API for Calculator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CalculatorClient interface {
	NthFibonacci(ctx context.Context, in *FibonacciParams, opts ...grpc.CallOption) (*NthFibonacciResponse, error)
	Substrings(ctx context.Context, in *SubstringsParams, opts ...grpc.CallOption) (*SubstringsResponse, error)
}

type calculatorClient struct {
	cc grpc.ClientConnInterface
}

func NewCalculatorClient(cc grpc.ClientConnInterface) CalculatorClient {
	return &calculatorClient{cc}
}

func (c *calculatorClient) NthFibonacci(ctx context.Context, in *FibonacciParams, opts ...grpc.CallOption) (*NthFibonacciResponse, error) {
	out := new(NthFibonacciResponse)
	err := c.cc.Invoke(ctx, "/grpc.demo.Calculator/NthFibonacci", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calculatorClient) Substrings(ctx context.Context, in *SubstringsParams, opts ...grpc.CallOption) (*SubstringsResponse, error) {
	out := new(SubstringsResponse)
	err := c.cc.Invoke(ctx, "/grpc.demo.Calculator/Substrings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CalculatorServer is the server API for Calculator service.
// All implementations must embed UnimplementedCalculatorServer
// for forward compatibility
type CalculatorServer interface {
	NthFibonacci(context.Context, *FibonacciParams) (*NthFibonacciResponse, error)
	Substrings(context.Context, *SubstringsParams) (*SubstringsResponse, error)
	mustEmbedUnimplementedCalculatorServer()
}

// UnimplementedCalculatorServer must be embedded to have forward compatible implementations.
type UnimplementedCalculatorServer struct {
}

func (UnimplementedCalculatorServer) NthFibonacci(context.Context, *FibonacciParams) (*NthFibonacciResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NthFibonacci not implemented")
}
func (UnimplementedCalculatorServer) Substrings(context.Context, *SubstringsParams) (*SubstringsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Substrings not implemented")
}
func (UnimplementedCalculatorServer) mustEmbedUnimplementedCalculatorServer() {}

// UnsafeCalculatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CalculatorServer will
// result in compilation errors.
type UnsafeCalculatorServer interface {
	mustEmbedUnimplementedCalculatorServer()
}

func RegisterCalculatorServer(s grpc.ServiceRegistrar, srv CalculatorServer) {
	s.RegisterService(&Calculator_ServiceDesc, srv)
}

func _Calculator_NthFibonacci_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FibonacciParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServer).NthFibonacci(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.demo.Calculator/NthFibonacci",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServer).NthFibonacci(ctx, req.(*FibonacciParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Calculator_Substrings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubstringsParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServer).Substrings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.demo.Calculator/Substrings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServer).Substrings(ctx, req.(*SubstringsParams))
	}
	return interceptor(ctx, in, info, handler)
}

// Calculator_ServiceDesc is the grpc.ServiceDesc for Calculator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Calculator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.demo.Calculator",
	HandlerType: (*CalculatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NthFibonacci",
			Handler:    _Calculator_NthFibonacci_Handler,
		},
		{
			MethodName: "Substrings",
			Handler:    _Calculator_Substrings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "calculator.proto",
}
