// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CalculatorClient is the client API for Calculator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CalculatorClient interface {
	NthFibonacci(ctx context.Context, in *FibonacciParams, opts ...grpc.CallOption) (*NthFibonacciResponse, error)
	Sum(ctx context.Context, in *SumParams, opts ...grpc.CallOption) (*SumResponse, error)
	RandomStream(ctx context.Context, in *RandomStreamParams, opts ...grpc.CallOption) (Calculator_RandomStreamClient, error)
}

type calculatorClient struct {
	cc grpc.ClientConnInterface
}

func NewCalculatorClient(cc grpc.ClientConnInterface) CalculatorClient {
	return &calculatorClient{cc}
}

func (c *calculatorClient) NthFibonacci(ctx context.Context, in *FibonacciParams, opts ...grpc.CallOption) (*NthFibonacciResponse, error) {
	out := new(NthFibonacciResponse)
	err := c.cc.Invoke(ctx, "/grpc.demo.Calculator/NthFibonacci", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calculatorClient) Sum(ctx context.Context, in *SumParams, opts ...grpc.CallOption) (*SumResponse, error) {
	out := new(SumResponse)
	err := c.cc.Invoke(ctx, "/grpc.demo.Calculator/Sum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calculatorClient) RandomStream(ctx context.Context, in *RandomStreamParams, opts ...grpc.CallOption) (Calculator_RandomStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Calculator_ServiceDesc.Streams[0], "/grpc.demo.Calculator/RandomStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculatorRandomStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Calculator_RandomStreamClient interface {
	Recv() (*RandomNumber, error)
	grpc.ClientStream
}

type calculatorRandomStreamClient struct {
	grpc.ClientStream
}

func (x *calculatorRandomStreamClient) Recv() (*RandomNumber, error) {
	m := new(RandomNumber)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CalculatorServer is the server API for Calculator service.
// All implementations must embed UnimplementedCalculatorServer
// for forward compatibility
type CalculatorServer interface {
	NthFibonacci(context.Context, *FibonacciParams) (*NthFibonacciResponse, error)
	Sum(context.Context, *SumParams) (*SumResponse, error)
	RandomStream(*RandomStreamParams, Calculator_RandomStreamServer) error
	mustEmbedUnimplementedCalculatorServer()
}

// UnimplementedCalculatorServer must be embedded to have forward compatible implementations.
type UnimplementedCalculatorServer struct {
}

func (UnimplementedCalculatorServer) NthFibonacci(context.Context, *FibonacciParams) (*NthFibonacciResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NthFibonacci not implemented")
}
func (UnimplementedCalculatorServer) Sum(context.Context, *SumParams) (*SumResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sum not implemented")
}
func (UnimplementedCalculatorServer) RandomStream(*RandomStreamParams, Calculator_RandomStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method RandomStream not implemented")
}
func (UnimplementedCalculatorServer) mustEmbedUnimplementedCalculatorServer() {}

// UnsafeCalculatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CalculatorServer will
// result in compilation errors.
type UnsafeCalculatorServer interface {
	mustEmbedUnimplementedCalculatorServer()
}

func RegisterCalculatorServer(s grpc.ServiceRegistrar, srv CalculatorServer) {
	s.RegisterService(&Calculator_ServiceDesc, srv)
}

func _Calculator_NthFibonacci_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FibonacciParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServer).NthFibonacci(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.demo.Calculator/NthFibonacci",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServer).NthFibonacci(ctx, req.(*FibonacciParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Calculator_Sum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SumParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServer).Sum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.demo.Calculator/Sum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServer).Sum(ctx, req.(*SumParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Calculator_RandomStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RandomStreamParams)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CalculatorServer).RandomStream(m, &calculatorRandomStreamServer{stream})
}

type Calculator_RandomStreamServer interface {
	Send(*RandomNumber) error
	grpc.ServerStream
}

type calculatorRandomStreamServer struct {
	grpc.ServerStream
}

func (x *calculatorRandomStreamServer) Send(m *RandomNumber) error {
	return x.ServerStream.SendMsg(m)
}

// Calculator_ServiceDesc is the grpc.ServiceDesc for Calculator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Calculator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.demo.Calculator",
	HandlerType: (*CalculatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NthFibonacci",
			Handler:    _Calculator_NthFibonacci_Handler,
		},
		{
			MethodName: "Sum",
			Handler:    _Calculator_Sum_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RandomStream",
			Handler:       _Calculator_RandomStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "calculator.proto",
}
